### ISSUE TITLE
Can't compile because of filter.cpp

### ISSUE THREAD

**Issue by sephina** [wg-perception/PartsBasedDetector#41]
When running the makefile I'm getting errors related to opencv, starts with "error: unknown type name 'Scalar'" and a full list of this type, at the file "filter.cpp".
I've tried to include an opencv library at the beginning, and then I'm getting "opencv2/imgproc/hal/hal.hpp' file not found".
So I've tried to change this include to include the file "imgproc.hpp" instead, but then I'm getting a list of errors: "error: use of undeclared identifier 'BaseRowFilter', 'BaseColumnFilter', 'BaseFilter' ..."

Do you have any idea for me?
I'm trying to compile on OSX 10.11 El Capitan with opencv 3.1.0

Thanks

**Comment by springzfx** [comment]
1. 
roll back to this commit 
![image](https://cloud.githubusercontent.com/assets/8992037/20974880/938a22e2-bcd8-11e6-8d01-b6531dcb453b.png)

2. 
replace src/filter.cpp line 44 
`#include <opencv2/imgproc/hal/hal.hpp>` 
to
`#include <opencv2/core/hal/hal.hpp>`
